### PR TITLE
Improve the docstrings for polar co-ordinates

### PR DESCRIPTION
**Pull request by Adimote**
Currently they're `#TODOs`

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
The polar coordinates are deprecated and undocumented. I'm not sure I see the point in this?

**Comment by PeterJCLaw** [comment]
See https://github.com/sourcebots/docs/pull/67#discussion_r165389391 for the previous investigation into the current `polar` coordinates; I've summarised the interesting part below since I suspect that comment will be collapsed if you click through.

`sb-vision`'s `polar_x` and `polar_y` are calculated by [`cartesian_to_polar`](https://github.com/sourcebots/sb-vision/blob/57675c144b89eedb7ef451483c5a69412bc44d4a/sb_vision/tokens.py#L161) and translate to `rot_x...` and `rot_y...` respectively on the `robot-api` side. These values are not really in the right pace to be used (they're the wrong side of the triangle) and they also express a "rotation along the {x,y} axis" rather than "rotation about the {x,y} axis".

vision-reference-current-polar-implementation

**Comment by kierdavis** [comment]
Oops, I assumed this PR was regarding spherical coordinates rather than polar when I looked over it earlier.

I concur with @PeterJCLaw here - now that spherical is shipped and polar is officially deprecated, why are we still caring about this?

**Comment by Adimote** [comment]
Good point, I're replaced them all with Deprecated

**Pull request merged**
